# Generated by Django 3.0.9 on 2020-08-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientErip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('Минск', 'Минск'), ('Брест', 'Брест'), ('Витебск', 'Витебск'), ('Гомель', 'Гомель'), ('Гродно', 'Гродно'), ('Могилев', 'Могилев')], max_length=30, verbose_name='Регион')),
                ('date_add_card', models.DateTimeField(verbose_name='Дата заведения карточки')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование')),
                ('enter_point', models.CharField(max_length=30, verbose_name='Точка входа')),
                ('unp', models.CharField(max_length=20, verbose_name='УНП')),
                ('kind_of_activity', models.CharField(max_length=30, verbose_name='Вид деятельности')),
                ('leader', models.CharField(max_length=30, verbose_name='Руководитель (ЛПР)')),
                ('contact_face', models.CharField(max_length=30, verbose_name='Контактное лицо')),
                ('number', models.CharField(help_text='Введите телефон в международном формате +375*********', max_length=20, verbose_name='Телефон')),
                ('email', models.CharField(max_length=20, verbose_name='E-mail')),
                ('site', models.CharField(max_length=30, verbose_name='Сайт')),
                ('service', models.CharField(max_length=30, verbose_name='Сервис')),
                ('status', models.CharField(choices=[('Подключен', 'Подключен'), ('Не одключен', 'Не подключен'), ('Отключен', 'Отключен')], max_length=20, verbose_name='Статус')),
                ('type_of_appeal', models.CharField(max_length=30, verbose_name='Текущее мероприятие')),
                ('event_date', models.DateTimeField(verbose_name='Дата мероприятия')),
                ('aggregator', models.CharField(max_length=30, verbose_name='Агрегатор')),
                ('date_sending_application', models.DateTimeField(verbose_name='Дата договора')),
                ('additional_information', models.CharField(max_length=30, verbose_name='Номер договора')),
            ],
        ),
    ]
