# Generated by Django 3.0.9 on 2020-08-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200804_1659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
