# Generated by Django 3.0.9 on 2020-08-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200804_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='GOOD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prochee', models.CharField(max_length=30, verbose_name='Прочее')),
            ],
        ),
        migrations.DeleteModel(
            name='GOOOG',
        ),
        migrations.AlterModelOptions(
            name='clienterip',
            options={'verbose_name': 'Клиента', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
