# Generated by Django 3.0.9 on 2020-08-04 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200804_1720'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GOOD',
        ),
    ]
