# Generated by Django 3.0.9 on 2020-08-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20200805_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COOL', models.CharField(max_length=30, verbose_name='Наименование')),
                ('kind_of_activity', models.CharField(max_length=30, verbose_name='Вид деятельности')),
            ],
        ),
        migrations.DeleteModel(
            name='FUCK',
        ),
    ]
